name: .NET Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - uses: actions/checkout@master
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Restore
      run: nuget restore /PackagesDirectory src\packages
    
    - name: MSBuild
      working-directory: src
      run: msbuild AbeckDev.AzureKinectSensorConnector.csproj  /t:Build /p:Configuration=Release /p:Platform=x64 /p:TargetFramework=v4.8

    - name: list results (Debug)
      run: pwd && ls
      
    - name: NuGet Pack
      working-directory: src
      run: nuget pack AbeckDev.AzureKinectSensorConnector.csproj

    - name: list results (Debug)
      run: pwd && ls

